### ISSUE TITLE
Getting "Undefined constant LOG_PATH" Error on Startup

### ISSUE THREAD

**Issue by ghost** [movim/movim_docker#34]
Running docker-compose results in the movim service exiting on error:

docker-compose.yml:
```yml
services:
  movim:
    environment:
      MOVIM_DOMAIN: http://localhost
      MOVIM_PORT: 8080
      MOVIM_INTERFACE: 0.0.0.0
      POSTGRES_DB: movim
      POSTGRES_HOST: postgresql
      POSTGRES_PORT: 5432
      POSTGRES_USER: movim
      POSTGRES_PASSWORD: <password>
    image: movim/movim:0.21rc5
    volumes:
    - ${PWD}/movim:/var/www/html:rw

  nginx:
    image: nginx:mainline-alpine
    ports:
    - published: 3030
      target: 80
    volumes:
    - ${PWD}/movim:/var/www/html:ro
    - ${PWD}/nginx:/etc/nginx/conf.d:ro

  postgresql:
    environment:
      POSTGRES_DB: movim
      POSTGRES_PASSWORD: <password>
      POSTGRES_USER: movim
    image: postgres:15-alpine
    volumes:
    - ${PWD}/postgres/data:/var/lib/postgresql/data:rw
version: '3.8'
```

Applicable logs:
```
movim-movim-1       | Phinx by CakePHP - https://phinx.org.
movim-movim-1       | 
movim-movim-1       | using config file phinx.php
movim-movim-1       | 
movim-movim-1       | Fatal error: Uncaught Error: Undefined constant "LOG_PATH" in /var/www/html/app/helpers/UtilsHelper.php:19
movim-movim-1       | Stack trace:
movim-movim-1       | #0 /var/www/html/src/Movim/Bootstrap.php(307): Utils::error('Error: Undefine...')
movim-movim-1       | #1 /var/www/html/src/Movim/Bootstrap.php(320): Movim\Bootstrap->systemErrorHandler(1, 'Error: Undefine...', '/var/www/html/a...', 19, '#0 /var/www/htm...')
movim-movim-1       | #2 [internal function]: Movim\Bootstrap->exceptionHandler(Object(Error))
movim-movim-1       | #3 {main}
movim-movim-1       |   thrown in /var/www/html/app/helpers/UtilsHelper.php on line 19
movim-movim-1       | 
movim-movim-1       | Fatal error: Uncaught Error: Undefined constant "LOG_PATH" in /var/www/html/app/helpers/UtilsHelper.php:19
movim-movim-1       | Stack trace:
movim-movim-1       | #0 /var/www/html/src/Movim/Bootstrap.php(307): Utils::error('Uncaught Error:...')
movim-movim-1       | #1 /var/www/html/src/Movim/Bootstrap.php(332): Movim\Bootstrap->systemErrorHandler(1, 'Uncaught Error:...', '/var/www/html/a...', 19)
movim-movim-1       | #2 [internal function]: Movim\Bootstrap->fatalErrorShutdownHandler()
movim-movim-1       | #3 {main}
movim-movim-1       |   thrown in /var/www/html/app/helpers/UtilsHelper.php on line 19
```

**Comment by thundergreen** [comment]
nice one .. have the same error :/ any idea on this?

**Comment by kawaii** [comment]
Taking a look at this today, not had it personally though.

**Comment by kawaii** [comment]
Looks like I need to wait for edhelas to resolve this and push a new RC, then I'll be able to build a fixed image.

**Comment by edhelas** [comment]
This should fix it https://github.com/movim/movim/commit/3cc04a771ff431b23ecfdc55ab3de8dc65e8b6b9
Also available in the recently taggued 0.21rc7

**Comment by kawaii** [comment]
> This should fix it [movim/movim@3cc04a7](https://github.com/movim/movim/commit/3cc04a771ff431b23ecfdc55ab3de8dc65e8b6b9) Also available in the recently taggued 0.21rc7

```
movim-movim-1  | Fatal error: Uncaught Error: Undefined constant "LOG_PATH_RESOLVED" in /var/www/html/app/helpers/UtilsHelper.php:19
movim-movim-1  | Stack trace:
movim-movim-1  | #0 /var/www/html/src/Movim/Bootstrap.php(302): Utils::error('Error: Undefine...')
movim-movim-1  | #1 /var/www/html/src/Movim/Bootstrap.php(310): Movim\Bootstrap->systemErrorHandler(1, 'Error: Undefine...', '/var/www/html/a...', 19, '#0 /var/www/htm...')
movim-movim-1  | #2 [internal function]: Movim\Bootstrap->exceptionHandler(Object(Error))
movim-movim-1  | #3 {main}
movim-movim-1  |   thrown in /var/www/html/app/helpers/UtilsHelper.php on line 19
```
@edhelas looks like a slightly different error now with the new RC.

**Comment by aboveagency** [comment]
hi folks. @edhelas @kawaii thank you for your hard work on mov.im 

was attempting to deploy an instance today and ran into the same issue with constant 'LOG_PATH' - looking forward to a fix. :)

**Comment by glward** [comment]
Ran into the same issue, but I was able to work around it by creating a .env file and explicitly adding the paths to it, as well as setting all the other needed variables:

```
...
LOG_PATH=/var/www/html/log
CACHE_PATH=/var/www/html/cache
```

though I swear it seems like the cache stuff got dumped right into `/var/www/html` and not the cache subfolder.

It then started complaining about `--url` not being a valid argument so I had to modify the command run by docker-compose (since I made a .env file, I just set the url/etc there):

```
services:
  movim:
    environment:
       ...
    image: movim/movim:latest
    volumes:
      - ./movim:/var/www/html:rw
    command: ["su", "-s", "/bin/sh", "-c", "php daemon.php start --verbose --debug", "www-data"]
```

Been working fine for a few days now with those tweaks, at least for my one-user instance.

**Comment by aboveagency** [comment]
> 



> Ran into the same issue, but I was able to work around it by creating a .env file and explicitly adding the paths to it, as well as setting all the other needed variables:
> 
> ```
> ...
> LOG_PATH=/var/www/html/log
> CACHE_PATH=/var/www/html/cache
> ```
> 
> though I swear it seems like the cache stuff got dumped right into `/var/www/html` and not the cache subfolder.
> 
> It then started complaining about `--url` not being a valid argument so I had to modify the command run by docker-compose (since I made a .env file, I just set the url/etc there):
> 
> ```
> services:
>   movim:
>     environment:
>        ...
>     image: movim/movim:latest
>     volumes:
>       - ./movim:/var/www/html:rw
>     command: ["su", "-s", "/bin/sh", "-c", "php daemon.php start --verbose --debug", "www-data"]
> ```
> 
> Been working fine for a few days now with those tweaks, at least for my one-user instance.

I appreciate you sharing that, unfortunately still having issues with the LOG_PATH constant. I defined the environment variables one by one within the environment block as you have, and separately within an environment file.  Evaluated LOG_PATH using docker-compose convert to ensure they were set, and yet still getting the undefined constant issue.

**Comment by glward** [comment]
FWIW I had to completely delete the movim folder after many trials and start it the first time with the fully-populated .env file as the only file in that folder. I think some stuff might have gotten cached from my various failed attempts.
